// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/studio/login': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/studio/login.get').default>>>>
    }
    '/api/studio/logout': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/studio/logout.get').default>>>>
    }
    '/rss.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/rss.xml').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+nitro-server@4.4.2_@babel+core@7.29.0_better-sqlite3@12.8.0_db0@0.3.4_better-sqli_393d79e39705ac68029da3bd16f5cba2/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@2.2.1_magicast@0.5.2_vite@7.3.1_@types+node@25.5.0_jiti@2.6.1_lightningcss@1_dafee9dd5d55e91ecb455eeceb45ba8b/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/__nuxt_studio/dev/content/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-studio@1.4.0_db0@0.3.4_better-sqlite3@12.8.0__ioredis@5.10.0_magicast@0.5.2_vue@3.5.30_typescript@5.9.3_/node_modules/nuxt-studio/dist/module/runtime/server/routes/dev/content/[...path]').default>>>>
    }
    '/__nuxt_studio/dev/public/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-studio@1.4.0_db0@0.3.4_better-sqlite3@12.8.0__ioredis@5.10.0_magicast@0.5.2_vue@3.5.30_typescript@5.9.3_/node_modules/nuxt-studio/dist/module/runtime/server/routes/dev/public/[...path]').default>>>>
    }
    '/__nuxt_studio/auth/github': {
      'GET': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-studio@1.4.0_db0@0.3.4_better-sqlite3@12.8.0__ioredis@5.10.0_magicast@0.5.2_vue@3.5.30_typescript@5.9.3_/node_modules/nuxt-studio/dist/module/runtime/server/routes/auth/github.get').default>>>>
    }
    '/__nuxt_studio/auth/google': {
      'GET': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-studio@1.4.0_db0@0.3.4_better-sqlite3@12.8.0__ioredis@5.10.0_magicast@0.5.2_vue@3.5.30_typescript@5.9.3_/node_modules/nuxt-studio/dist/module/runtime/server/routes/auth/google.get').default>>>>
    }
    '/__nuxt_studio/auth/gitlab': {
      'GET': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-studio@1.4.0_db0@0.3.4_better-sqlite3@12.8.0__ioredis@5.10.0_magicast@0.5.2_vue@3.5.30_typescript@5.9.3_/node_modules/nuxt-studio/dist/module/runtime/server/routes/auth/gitlab.get').default>>>>
    }
    '/__nuxt_studio/auth/sso': {
      'GET': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-studio@1.4.0_db0@0.3.4_better-sqlite3@12.8.0__ioredis@5.10.0_magicast@0.5.2_vue@3.5.30_typescript@5.9.3_/node_modules/nuxt-studio/dist/module/runtime/server/routes/auth/sso.get').default>>>>
    }
    '/__nuxt_studio/auth/session': {
      'GET': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-studio@1.4.0_db0@0.3.4_better-sqlite3@12.8.0__ioredis@5.10.0_magicast@0.5.2_vue@3.5.30_typescript@5.9.3_/node_modules/nuxt-studio/dist/module/runtime/server/routes/auth/session.get').default>>>>
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-studio@1.4.0_db0@0.3.4_better-sqlite3@12.8.0__ioredis@5.10.0_magicast@0.5.2_vue@3.5.30_typescript@5.9.3_/node_modules/nuxt-studio/dist/module/runtime/server/routes/auth/session.delete').default>>>>
    }
    '/_studio': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-studio@1.4.0_db0@0.3.4_better-sqlite3@12.8.0__ioredis@5.10.0_magicast@0.5.2_vue@3.5.30_typescript@5.9.3_/node_modules/nuxt-studio/dist/module/runtime/server/routes/admin').default>>>>
    }
    '/__nuxt_studio/meta': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-studio@1.4.0_db0@0.3.4_better-sqlite3@12.8.0__ioredis@5.10.0_magicast@0.5.2_vue@3.5.30_typescript@5.9.3_/node_modules/nuxt-studio/dist/module/runtime/server/routes/meta').default>>>>
    }
    '/sw.js': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-studio@1.4.0_db0@0.3.4_better-sqlite3@12.8.0__ioredis@5.10.0_magicast@0.5.2_vue@3.5.30_typescript@5.9.3_/node_modules/nuxt-studio/dist/module/runtime/server/routes/sw').default>>>>
    }
    '/__site-config__/debug.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-site-config@3.2.21_magicast@0.5.2_vite@7.3.1_@types+node@25.5.0_jiti@2.6.1_lightni_771a32fce14216811a05d2e4a52f4f33/node_modules/nuxt-site-config/dist/runtime/server/routes/__site-config__/debug').default>>>>
    }
    '/__sitemap__/nuxt-content-urls.json': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.6.0_magicast@0.5.2_vite@7.3.1_@types+node@25.5.0_jiti@2.6.1_lightning_6928f0e02ba672570dc513d6d2e47798/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/__sitemap__/nuxt-content-urls-v3').default>>>>
    }
    '/__sitemap__/style.xsl': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.6.0_magicast@0.5.2_vite@7.3.1_@types+node@25.5.0_jiti@2.6.1_lightning_6928f0e02ba672570dc513d6d2e47798/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/sitemap.xsl').default>>>>
    }
    '/sitemap.xml': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxtjs+sitemap@7.6.0_magicast@0.5.2_vite@7.3.1_@types+node@25.5.0_jiti@2.6.1_lightning_6928f0e02ba672570dc513d6d2e47798/node_modules/@nuxtjs/sitemap/dist/runtime/server/routes/__zero-runtime/sitemap.xml').default>>>>
    }
    '/__nuxt_content/content/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.8.0_magicast@0.5.2_valibot@1.2.0_typescript@5.9.3_/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/blog/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.8.0_magicast@0.5.2_valibot@1.2.0_typescript@5.9.3_/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/homepage/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.8.0_magicast@0.5.2_valibot@1.2.0_typescript@5.9.3_/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/__nuxt_content/info/sql_dump.txt': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.8.0_magicast@0.5.2_valibot@1.2.0_typescript@5.9.3_/node_modules/@nuxt/content/dist/runtime/presets/node/database-handler').default>>>>
    }
    '/api/component-meta': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-component-meta@0.17.2_magicast@0.5.2/node_modules/nuxt-component-meta/dist/runtime/server/api/component-meta.get').default>>>>
    }
    '/api/component-meta.json': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-component-meta@0.17.2_magicast@0.5.2/node_modules/nuxt-component-meta/dist/runtime/server/api/component-meta.json.get').default>>>>
    }
    '/api/component-meta/:component?': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-component-meta@0.17.2_magicast@0.5.2/node_modules/nuxt-component-meta/dist/runtime/server/api/component-meta-component.get').default>>>>
    }
    '/__nuxt_content/content/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.8.0_magicast@0.5.2_valibot@1.2.0_typescript@5.9.3_/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/blog/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.8.0_magicast@0.5.2_valibot@1.2.0_typescript@5.9.3_/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/homepage/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.8.0_magicast@0.5.2_valibot@1.2.0_typescript@5.9.3_/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/__nuxt_content/info/query': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+content@3.12.0_better-sqlite3@12.8.0_magicast@0.5.2_valibot@1.2.0_typescript@5.9.3_/node_modules/@nuxt/content/dist/runtime/api/query.post').default>>>>
    }
    '/_ipx/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+image@2.0.0_db0@0.3.4_better-sqlite3@12.8.0__ioredis@5.10.0_magicast@0.5.2/node_modules/@nuxt/image/dist/runtime/server/routes/_ipx').default>>>>
    }
  }
}
export {}