import type { PageCollectionItemBase, DataCollectionItemBase } from '@nuxt/content'

declare module '@nuxt/content' {
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface ContentCollectionItem extends PageCollectionItemBase {
    layout?: string;
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface BlogCollectionItem extends PageCollectionItemBase {
    title: string;
    description?: string;
    date?: string;
    author?: string;
    category?: string;
    slug?: string;
    layout?: string;
    draft?: boolean;
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface HomepageCollectionItem extends DataCollectionItemBase {
    hero: {
    title: string;
    subtitle: string;
    description: string;
    };
    sections: {
    id: string;
    title: string;
    subtitle?: string;
    type: "text" | "infrastructure" | "software" | "cta";
    content?: string;
    list?: {
      title: string;
      text: string;
    }[];
    quote?: string;
    items?: unknown[];
    }[];
    footer: {
    lastUpdated: string;
    statusUrl: string;
    };
  }
  

  interface PageCollections {
    content: ContentCollectionItem
    blog: BlogCollectionItem
  }

  interface Collections {
    content: ContentCollectionItem
    blog: BlogCollectionItem
    homepage: HomepageCollectionItem
  }
}
